-- "nvim-tree/nvim-tree.lua",
-- cmd = { "NvimTreeToggle", "NvimTreeFocus" },
-- local opts = {
--     -- require("nvchad.configs.nvimtree"),
--     renderer = {
--         icons = {
--             git_placement = "after",
--             symlink_arrow = "->>",
--         },
--     },
-- },
--
--
-- require("nvim-tree").setup(opts)
--
return {
    -- "nvim-tree/nvim-tree.lua",
    -- -- cmd = { "NvimTreeToggle", "NvimTreeFocus" },
    -- opts = {
    --     renderer = {
    --         icons = {
    --             git_placement = "after",
    --             symlink_arrow = "->",
    --         },
    --     },
    -- },
    
    -- -- return require("nvchad.configs.nvimtree")
    -- config = function(_, opts)
    --     dofile(vim.g.base46_cache .. "nvimtree")
    --     require("nvim-tree").setup(opts)
    -- end,
}
